LCM = lcm-gen

LCMTYPES_NAMES := $(shell cd ../lcmtypes && ls *.lcm)

# Construct the pathnames to the java types.
LCMTYPES_JAVA := $(LCMTYPES_NAMES:%.lcm=%.java)
LCMTYPES_JAVA := $(addprefix src/abolt/lcmtypes/,$(LCMTYPES_JAVA))

SUFFIXES += .java .lcm

all:    $(LCMTYPES_JAVA)


src/abolt/lcmtypes/%.java: ../lcmtypes/%.lcm
	$(LCM) -j  --jpath=src --jdefaultpkg=abolt.lcmtypes $<

clean:
	rm -rf *~ src/abolt/lcmtypes/*
